// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogCategory struct {
	CategoryID          pgtype.UUID `json:"category_id"`
	CategoryName        pgtype.Text `json:"category_name"`
	CategoryDescription pgtype.Text `json:"category_description"`
}

type CatalogCategoryLink struct {
	CategoryLinkID   pgtype.UUID `json:"category_link_id"`
	MainCategoryID   pgtype.UUID `json:"main_category_id"`
	LinkedCategoryID pgtype.UUID `json:"linked_category_id"`
}

type CatalogItem struct {
	ItemID                 pgtype.UUID `json:"item_id"`
	ItemTitle              pgtype.Text `json:"item_title"`
	ManufacturerID         pgtype.UUID `json:"manufacturer_id"`
	ManufacturerNameLine   pgtype.Text `json:"manufacturer_name_line"`
	ManufacturerOriginalID pgtype.Text `json:"manufacturer_original_id"`
}

type CatalogItemCategorized struct {
	ItemCategorizedID pgtype.UUID `json:"item_categorized_id"`
	ItemID            pgtype.UUID `json:"item_id"`
	CategoryLeafID    pgtype.UUID `json:"category_leaf_id"`
}

type CatalogItemDescription struct {
	ItemID      pgtype.UUID `json:"item_id"`
	Description pgtype.Text `json:"description"`
}

type CatalogItemImage struct {
	ItemImageID pgtype.UUID `json:"item_image_id"`
	ItemID      pgtype.UUID `json:"item_id"`
	Image       []byte      `json:"image"`
}

type CatalogItemRetailPrice struct {
	ItemID      pgtype.UUID `json:"item_id"`
	RetailPrice pgtype.Int4 `json:"retail_price"`
	CurrencyID  pgtype.UUID `json:"currency_id"`
}
